# Good for CartPole-v1
# 24635 params
dqn:
  layers: [153, 153]

# 24594 params -> rules does not affect the parameters
anfis:
  layers: [128, 128]
  n_rules: 16
  defuzz_layers: [64, 64]

general:
  type: anfis
  device: cuda
  seed: 109

optimizer:
  type: Adam
  lr: 1.0e-4

loss:
  type: mse

memory:
  max_len: 10_000

training:
  env: CartPole-v1
  n_iterations: 70_000
  batch_size: 64
  gamma: 0.99
  update_every: 100
  train_after: 1_000
  tau: 1.0e-3
  log_every: 100
  epsilon_n_decay: 15_000
  epsilon_start: .99
  epsilon_end: .01
  gradient_steps: 1
  grad_norm: 10

testing:
  n_epiosdes: 10
  test_every: 10_000
